* pandas是基于Numpy数组构建的，二者最大的不同是Pandas是专门为处理表格和混杂数据设计的，而Numpy更适合处理统一的数值数组数据
* 首先导入包

In [2]:
import pandas as pd
from pandas import Series, DataFrame

# 5.1pandas的数据结构介绍
* pandas的两个主要数据结构是Series和DataFrame.
## Series
* Series是一种类似于数组的对象，它由一组数据和一组与数据相关的数据标签（索引）组成，仅由一组数据就可以产生最简单的Series.
* Series的字符串表现形式为左边为索引，右边为该索引对应的值。当没有指定索引时，自动按0—N-1的整型索引。

In [5]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

* 可以通过values和index获得其数组表现形式的值和索引

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
list(obj.index)

[0, 1, 2, 3]

* 也可以为值指定索引

In [12]:
obj2 = pd.Series([1,9,-3,19],index = ['a', 'b', 'c', 'd'])
obj2

a     1
b     9
c    -3
d    19
dtype: int64

In [13]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [20]:
print(obj2['a'])
print(obj[['a', 'c','d']])

1
a     1
c    -3
d    19
dtype: int64


* 使用NumPy函数或类似NumPy的运算（如根据布尔型数组进行过滤、标量乘法、应用数学函数等）都会保留索引值的链接

In [21]:
obj2[obj2>4]

b     9
d    19
dtype: int64

In [23]:
obj2>4

a    False
b     True
c    False
d     True
dtype: bool

In [24]:
obj2 * 2

a     2
b    18
c    -6
d    38
dtype: int64

In [27]:
import numpy as np
np.exp(obj2)  #不改变原对象

a    2.718282e+00
b    8.103084e+03
c    4.978707e-02
d    1.784823e+08
dtype: float64

In [28]:
obj2

a     1
b     9
c    -3
d    19
dtype: int64

* 可以将Series看成一个定长的有序字典

In [29]:
'b' in obj2

True

In [31]:
'e' in obj2

False

* 如果数据原本存放在python的字典中，可以直接将其转换为Serie

In [35]:
dict_data = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
s_data = pd.Series(dict_data)
s_data

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
dict_data

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

* 如果只传入一个字典，则结果Series的索引就是字典的键。但是也可以传入一个排好序的键改变顺序

In [38]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj3 = pd.Series(dict_data, index = states)
obj3

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

* NaN即not a number,用于表示缺失值或者NA值。可以用isnull和notnull函数检查缺失的数据

In [39]:
pd.isnull(obj3)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [41]:
pd.notnull(obj3)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [42]:
obj3.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

* Series最重要的功能是，它会根据运算的索引标签自动的对其value

In [44]:
obj3 + s_data

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

* Series对象本身和其索引都有一个name属性

In [48]:
obj3.name = 'population'
obj3.index.name = 'state'
obj3

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

* Series的索引可以通过赋值就地修改

In [53]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [54]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [55]:
obj.name = 'score'
obj.index.name = 'name'

In [57]:
obj.name

'score'

In [58]:
obj.index.name

'name'

## DataFrame
* DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。DataFrame既有行索引也有列索引
* DataFrame中的数据是以一个或多个二维块存放的（而不是列表、字典或别的一维数据结构）

* 构建DataFrame最常用的方式是直接传入一个由等长的列表或者numpy数组组成的字典

In [60]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

* 对于特别大的DataFrame，head方法会选取前5行

In [61]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

* 如果指定了列顺序，就会按照指定序列排序

In [63]:
pd.DataFrame(data,columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

* 如果传入的列在数据中找不到，就会产生缺失值

In [64]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

* 通过类似字典的方式或属性的方式，可以将DataFrame的列获取为一个Series

In [65]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [66]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

* 行也可以通过位置或者名称的方式获取，比如loc属性

In [67]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

* 列可以通过赋值的方式进行修改

In [70]:
frame2.debt = 16.2  #也可以使用frame2['debt'] = 16.2
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.2
two    2001    Ohio  1.7  16.2
three  2002    Ohio  3.6  16.2
four   2001  Nevada  2.4  16.2
five   2002  Nevada  2.9  16.2
six    2003  Nevada  3.2  16.2

In [72]:
frame2.debt = np.arange(6)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

* 将列表或者数组赋值给某个列时，其长度必须于DataFrame的长度匹配。如果赋值的是Series，就会精确的匹配DataFrame的索引，并自动填补缺失值

In [73]:
val = pd.Series([-1.2, -1.5, -1.7],index = ['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

* 为不存在的列赋值会创建一个新的列

In [74]:
frame2['estern'] = (frame2.state=='Ohio')
frame2

year   state  pop  debt  estern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False

* 注意：上述代码并不能用frame2.estern创建新的列
* del 方法可以删除这列

In [76]:
del frame2['estern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [77]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

* 注意：通过索引的方式返回的列是相应数据的视图，对其返回的任何Series所做的修改都会反映到源DataFrame上。可以通过Series的copy方法复制指定的列

* 另一种常见的数据形式是嵌套字典。如果将嵌套字典传给DataFrame,pandas会将其解释为：外键作为列，内键作为行索引，并自动填补缺失值

In [81]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
       'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

* 可以像Numpy那样进行转置

In [82]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

* 内层字典的键会被合并、排序以形成最终的索引。如果指定了索引则不会这样：

* 由series组成的字典也是同样的用法

In [86]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

* 可以输入给DataFrame的数据类型如下表
<img src="data\5-1.png">


* 如果设置了DataFrame的index和columns的name属性，这些信息会被显示出来

In [87]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

* DataFrame也有values属性，并会以二维数组的形式返回

In [88]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

* 如果DataFrame各列的数据类型不同，则最终返回可以兼容所有列的数据类型

In [89]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象
* pandas的索引对象负责管理轴标签和其他元素（比如轴名称等）。构建Series或者DataFrame时，所用到的任何数组或者其他序列的标签都会被转换成一个Index

In [90]:
obj = pd.Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [92]:
index[1:]

Index(['b', 'c'], dtype='object')

In [94]:
# Index对象是不可变的
index[1]='d'

TypeError: Index does not support mutable operations

* 不可变可以使Index对象在多个数据结构之间安全的共享

In [98]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [99]:
obj2 = pd.Series([1.5,1.3,0],index=labels)
obj2

0    1.5
1    1.3
2    0.0
dtype: float64

In [100]:
obj2.index is labels

True

* 除了Index类似于数组，还类似于一个固定大小的字典

In [101]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [102]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [103]:
'Ohio' in frame3.columns

True

In [104]:
2000 in frame3.index

True

* 与python集合不同，Index可以包含重复的标签

In [105]:
dul_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dul_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

* Index的方法和属性见下表：
<img src="data/5-2.jpg">
